### PR TITLE
Legal action my ass kisak.

### PR DESCRIPTION
**Pull request by RandomTNT**
Revert everything that kisak has done
Continue pasting from quake engine vavlo

### CODE REVIEW

**Comment by RandomTNT** [comment]
why are you so hostile kisak

**Comment by RandomTNT** [comment]
if he deletes this shit of off GH might aswell as move to GL cant hurt no one on a private instance can you kisak?

**Comment by RandomTNT** [comment]
actually no fuck off after the arm cut off incident u aint getting my revert commit paster

**Comment by rosnegaming-v2** [comment]
good idea.

**Comment by WhoIsAsking1996** [comment]
Will not merge 🖕 🖕

**Pull request merged**
